language: node_js
node_js:
  - v6
  - v5
  - v4


after_success: npm run coveralls

branches:
  except:
    - gh-pages

# deploy:
#   skip_cleanup: true
#   provider: script
#   script: sh ./.deploy.sh
#   on:
#     branch: master
